### ISSUE TITLE
Rename some features

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Website#15]
Working on this app, I figured out that it is quite hard to grasp what this app does.

Perhaps renaming some features would help:

1. Rename **Templates** tab to **Surfaces**
   - Prism calls it "shells": https://msdn.microsoft.com/en-us/library/ff921098(v=pandp.40).aspx
   - Progressive Web Apps call it "shells": https://developers.google.com/web/fundamentals/architecture/app-shell
   - Material Design calls it "structures": https://material.io/guidelines/layout/structure.html#structure-ui-regions
2. In Surfaces list, rename the **Html** column to **View URI**
3. Rename **Sections** tab to **Blending points**.
   - Material Design calls it "regions": https://material.io/guidelines/layout/structure.html#structure-ui-regions
   - Prism calls it "regions": https://msdn.microsoft.com/en-us/library/ff921098(v=pandp.40).aspx
   - Marionette calls it "regions": http://marionettejs.com/docs/marionette.view.html#laying-out-views-regions
4. Rename **Urls** tab to **Catching rules**
5. In Shell rules list, rename the **Url** column to **Catch URI**
6. Rename **Maps** tab to **Pinning rules**
7. In the Pinning rules list, rename the **Section** column to **Blending point**
8. In the Pinning rules list, rename the **Url** column to **Catch URI**
9. In the Pinning rules list, rename the **Foreign url** column to **Pin URI**

Comments welcome.

**Comment by diliger** [comment]
Rename just titles or all references inside the project as well?

**Comment by warpech** [comment]
Whatever makes bigger sense.

Big first of all I want to get comments if you agree that this a change for better.

cc @miyconst WDYT?

**Comment by warpech** [comment]
I was discussing this with @tomalec on Friday. 

I had an idea to rename **Templates** to **Surfaces*. And then to rename **Sections** to **Insertion points** or **Includes**.

@tomalec have you slept on it, do you have some new proposals here?

**Comment by tomalec** [comment]
I like Surfaces.

I'd like to do another round of brainstorming, once the app's code is cleaned up, so we could reduce even more :>

**Comment by warpech** [comment]
I have changed the first post to contain the current proposal.

Please change texts, urls, view-model names and file names. Do NOT change Simplified class names.

This is not final change in the UI, in a next issue we want to streamline it more to look like CloudFlare:

<img width="1396" alt="screen shot 2017-02-10 at 12 01 28" src="https://cloud.githubusercontent.com/assets/566463/22824590/d32b132e-ef88-11e6-88db-d956693af7c7.png">

**Comment by warpech** [comment]
@diliger if you decide to work on this than this has now top priority for the Wednesday demo.

**Comment by warpech** [comment]
Taking this

**Comment by warpech** [comment]
Work in progress started in PR #36

**Comment by warpech** [comment]
Closing as done.
