### ISSUE TITLE
Put the template HTML in starcounter-composition

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Website#16]
The template HTMLs in `wwwroot/Website/templates/*.html` should make use of starcounter-composition. Then they become editable in CompositionEditor.

**Comment by diliger** [comment]
Should it be like this:
![image](https://cloud.githubusercontent.com/assets/15857369/22512250/640f7a7e-e8a9-11e6-914a-c0bfef9a6153.png)

Or something else?

`<content select="[slot='Website/Navigation']"></content>` - does it take the `OuterHtml` of the element or the `InnerHtml`?

And styles 
`<link href="/Website/css/AppHub.css" rel="stylesheet">`
where should it be placed? 
Inside template as before or inside `starcounter-composition`?

cc @warpech @tomalec

**Comment by tomalec** [comment]
> `<content select="[slot='Website/Navigation']"></content>` - does it take the `OuterHtml` of the element or the `InnerHtml`?

Neither. It takes the element.
https://www.w3.org/TR/shadow-dom/#shadow-tree
https://dom.spec.whatwg.org/#shadow-trees


> And styles...

I would put them outside of `<template>`.

**Comment by diliger** [comment]
So, am I correct with that `starcounter-composition`?

And do you mean to move styles link out?
![image](https://cloud.githubusercontent.com/assets/15857369/22544908/c8ee67c2-e947-11e6-9ce0-b10cf13ba7c2.png)

**Comment by tomalec** [comment]
Yes, if you really want to add styles only once partial is stamped you could add it between `<template>` and `<template is=dom-bind">`. But I strongly suggest to add such styles together with other links, as it's document-wide anyway.

**Comment by warpech** [comment]
Actually, I think that the `<section>` tags should be **in** starcounter-composition.

The same regarding AppHub.css, it should be **in** starcounter-composition, as:

```
<style>
@import url("/Website/css/AppHub.css");
</style>
```

**Comment by diliger** [comment]
you mean like this:
![image](https://cloud.githubusercontent.com/assets/15857369/22547744/35a3a4b6-e954-11e6-8a02-8b6d7b99484d.png)

**Comment by warpech** [comment]
Yes

**Comment by warpech** [comment]
Same for DefaultTemplate.html

**Comment by diliger** [comment]
check it now pls, PR #23

**Comment by diliger** [comment]
cc @warpech

**Comment by diliger** [comment]
Merged PR #23

**Comment by warpech** [comment]
Yay!
