### ISSUE TITLE
Changing sub-pages of an app reloads the whole app

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Website#17]
### Steps to reproduce

1. Start Website branch `develop`
2. Start People branch `fix-imported-template-26`
3. Start SignIn branch `develop`
4. Go to `http://localhost:8080/signin/generateadminuser` to generate the admin user
5. Go to `http://localhost:8080/people`
6. Sign in as admin user
7. Click on Organisations in the top menu
8. Click on People in the top menu

### Expected result

As you repeat steps 7-8 in a loop, the top menu should not reload. Only the nested `CurrentPage` should reload.

### Actual result

The whole People app reloads, including the top menu as well as the nested `CurrentPage`.

You can notice the problem because the menu text `Home - People - Organizations` changes the font and size after each click.

@chrhol any idea why this happens?

### Screenshot

![bug](https://cloud.githubusercontent.com/assets/566463/22165674/5ac9f4a8-df5d-11e6-9f66-a6b161e689b7.gif)

**Comment by chrhol** [comment]
> @chrhol any idea why this happens?

No, not really. As far as I can tell from debugging and looking at the patches, it looks fine. The section/row that contains the info is updated, but not the topbar (except some values for signin). 

Looking at it from the serverside there should be no reason for the menu to get reloaded.

![capture](https://cloud.githubusercontent.com/assets/1658979/22197017/54220ede-e150-11e6-8527-fcde2e5e97be.JPG)

**Comment by warpech** [comment]
Thank you very much for investigating this.

@diliger could you try investigating the client side? Why does it happen in your opinion?

**Comment by diliger** [comment]
After some testing I see the same, it is obvious though...

As we can see in the **patch**, it returns full `StandalonePage` for any new request, with `ShowMenu: true` and `standalone.css` styles.
So the full page gets refreshed.

I tested in Launcher and without Launcher, **patch** contains only the **CurrentPage** part.
![image](https://cloud.githubusercontent.com/assets/15857369/22369715/abce6aaa-e49e-11e6-8e03-dc03a4b3e22b.png)

So it should be somewhere on the server side, can anybody point me where to check?
cc @warpech

**Comment by warpech** [comment]
@diliger I tested the steps presented in the first comment and I get exactly the same patches as @chrhol. Are you sure you are following the same steps as we do?

Launcher is not part of this problem, this is between Website and People app. Launcher is not even running.

**Comment by warpech** [comment]
Actually the problem is exactly at the top of @chrhol's screenshot. 

The patch with the index 2 replaces `/TemplateModel/Sections/Main/Rows/0`.

It should replace `/TemplateModel/Sections/Main/Rows/0/People/CurrentPage`. Then the menu would not reload.

@chrhol any idea why is it so and how to fix that?

**Comment by warpech** [comment]
Ping @chrhol any news on this? This is very important for the Launcher revamp project.

**Comment by warpech** [comment]
To clarify what is reported by @diliger in the comment https://github.com/StarcounterPrefabs/Website/issues/17#issuecomment-275647541:

- the problem appears when running (Website + People + SignIn)
- it works as intended when running (People + SignIn) or (Launcher + People + SignIn)

**Comment by warpech** [comment]
It might be so because Launcher uses `workspace.MergeJson(resource);` and Website seems to repeat `Self.GET` on the same resource.

**Comment by warpech** [comment]
I have a solution. Will post it tomorrow.

**Comment by warpech** [comment]
Fixed in PR #22. @diliger thanks for inspiring me for the solution based on your observation.

**Comment by warpech** [comment]
Closing as done
