### ISSUE TITLE
Self.GET can only be to own URI

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Website#26]
Website app has a Self.GET to a URI starting with `/sc/mapping`. This is wrong. Self.GET should be only to own URIs, mapped to `/sc/mapping` (or equivalent: UriMapping.MappingUriPrefix) in a mapping file.

See how it was fixed in Launcher: https://github.com/StarcounterPrefabs/Launcher/pull/257/files

**Comment by diliger** [comment]
PR #27

**Comment by diliger** [comment]
Done.
