### ISSUE TITLE
Make Website CMS appear in its own default template

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Website#29]
Right now, Website CMS bypasses it's own wrapping rules. 

Let's make Website CMS wrap itself in a template, meaning: migrate `StandalonePage.html` a `Templates/WebsiteCMSTemplate.html` and set up `/website/cms/*` links to be wrapped by it.

**Comment by warpech** [comment]
I will work on it this weekend.

**Comment by warpech** [comment]
Implemented in PR #32

**Comment by warpech** [comment]
Closing as done

**Comment by diliger** [comment]
PR #38
