### ISSUE TITLE
Add a button to Restore the default surfaces

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Website#31]
We should make it impossible to delete the default template, because that is hard to recover. 

Or allow to revoke the default template with some button.

**Comment by warpech** [comment]
How about fixing it differently?

1) Clicking on an unchecked "Default", unchecks the previous default and checks the new one
2) Clicking on an checked "Default" does nothing
3) It is not possible to delete a template marked as "Default"

The same should apply for Sections:

1) When you create a Template/Surface, it always has one "Main" section/blending point that is marked as Default.
1) Clicking on an unchecked "Section", unchecks the previous default section in that template and checks the new one
2) Clicking on an checked "Default" does nothing
3) It is not possible to delete a section marked as "Default"

**Comment by diliger** [comment]
But in that way it is possible to have only one **Default** `Surface` at a time.
And I think that is not correct.
For example we may have `LauncherTemplate` and `DefaultTemplate` both as **Default**, don't we?

**Comment by warpech** [comment]
I think that it doesn't make sense to have two "Defaults", because what would that mean? This SQL query only cares about the first Default found: https://github.com/StarcounterPrefabs/Website/blob/8633a0cb821c5dbee341b18b5f1e2ba0d3bcba7a/src/WebsiteProvider/Api/ContentHandlers.cs#L103

Anyway, please disregard my above comments, because they conflict with PR #43.

**Comment by diliger** [comment]
I think that means it is the Final and shouldn't be wrapped again.

**Comment by diliger** [comment]
Closing as done.
