### ISSUE TITLE
DefaultTemplate TopBar appears wrong

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Website#33]
### Steps to reproduce

1. Start Website and WebsiteProvider (branch `feature/29-cms-default-template`)
2. Start SignIn branch `develop`
2. Start CompositionEditor branch `develop`
2. Call `http://localhost:8080/website/resetdata` to load default mappings
4. Go to `http://localhost:8080/signin/generateadminuser` to generate the admin user
5. Go to `http://localhost:8080/website/cms`
6. Sign in as admin user

### Expected result

In the top bar, on the right side of the screen, there should be two icons in the same row.

### Actual result

In Chrome, the icons appear in two different rows.

In Firefox, the icons appear on the left side on the screen and in two different rows.

This should be fixed the similarly to how it works in Launcher: https://github.com/StarcounterPrefabs/Launcher/blob/develop/src/Launcher/wwwroot/Launcher/viewmodels/LauncherUser.html, but without calling `:host` from the child page. Rather than that, fix the styles in: https://github.com/StarcounterPrefabs/Website/blob/feature/29-cms-default-template/src/Website/wwwroot/Website/templates/DefaultTemplate.html

@diliger can you pls take a look?
 
##### Browsers affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

#### Chrome

![2017-02-13 11_54_58-website - microsoft visual studio](https://cloud.githubusercontent.com/assets/566463/22881200/ca3d1302-f1e5-11e6-92e4-e8a9e442693a.png)

#### Firefox

![2017-02-13 11_57_59-website - microsoft visual studio](https://cloud.githubusercontent.com/assets/566463/22881207/cea3cf58-f1e5-11e6-9da1-67f86f76851c.png)

**Comment by diliger** [comment]
after some investigations.. I have a question here
to display it fine with css i should apply `display: flex;` for very nested `juicy-composition`
see the picture
![image](https://cloud.githubusercontent.com/assets/15857369/23097583/1b83bf66-f648-11e6-8495-9c88c47099cb.png)

the style created in `DefaultTemplate` is

> `.website-defaulttemplate-topbar ::content > starcounter-include`

but in my case it should be 

> `.website-defaulttemplate-topbar ::content > starcounter-include > juicy-composition > starcounter-include > juicy-composition`

I think it is a bit too long and unstable.

Another way is to fix it with `float: left;` applied to `<div class="icon-holder">` in 
[CompositionEditor/Master.html](https://github.com/Starcounter/CompositionEditor/blob/master/src/CompositionEditor/wwwroot/CompositionEditor/Master.html#L65)

**Comment by warpech** [comment]
Just use the same selectors as in LauncherTemplate.html: https://github.com/StarcounterPrefabs/Website/blob/3e8a7c0fbe770e0dc061c5448715259f8e9c9b7b/src/Website/wwwroot/Website/templates/LauncherTemplate.html#L179-L188

> Another way is to fix it with `float: left;` applied to `<div class="icon-holder">` in
CompositionEditor/Master.html

This is not good for two reasons: (1) floats are bad practice, (2) requires changing an app, which should not be needed. But I admire that you took the effort to investigate this option

**Comment by tomalec** [comment]
For Step "5. Go to http://localhost:8080/signin/generateadminuser to generate the admin user"

I get:
```
System.MissingMethodException: Nie odnaleziono metody: 'Void Starcounter.Db.Transact(System.Action, Boolean, Int32)'.
   w SignIn.SignInOut.AssureAdminSystemUser()
   w SignIn.MainHandlers.<Register>b__17(Request request) w d:\repos\PolyjuiceProjects\Polyjuice\SignIn\src\SignIn\Api\MainHandlers.cs:wiersz 132
   w Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) w C:\TeamCity\BuildAgent\work\sc-2538\Level1\src\Starcounter.Rest\UriHandlersManager.cs:wiersz 341
   w Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) w C:\TeamCity\BuildAgent\work\sc-2538\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:wiersz 98
   w Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) w C:\TeamCity\BuildAgent\work\sc-2538\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:wiersz 765
HResult=-2146233069

More information about this error may be available in the server error log.
```

Can you isolate it a littl bit more?

**Comment by Loudness** [comment]
@tomalec. I kept getting the Starcounter.Db.Transact MethodNotFoundException after updating  Starcounter. So, I recompiled the Signin project with the new starcounter installed and it worked. 
The method signature seem to change between versions, but that's just a guess.

**Comment by warpech** [comment]
> Starcounter 2.3.0.5701

[Simplified](https://github.com/StarcounterPrefabs/Simplified/commits/master) was last updated on Feb 16th. Please make sure you use Starcounter 2.3.0.5704 or newer.

**Comment by tomalec** [comment]
Thanks, that was it. I got it.

**Comment by warpech** [comment]
Done in #40
