### ISSUE TITLE
Add a "Final" property to Urls/Catching URIs

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Website#41]
### Steps to reproduce

1. Start Website and WebsiteProvider (branch `develop`)
2. Start SignIn branch `develop`
2. Call `http://localhost:8080/website/resetdata` to load default mappings
4. Go to `http://localhost:8080/signin/generateadminuser` to generate the admin user
5. Go to `http://localhost:8080/website/cms`
6. Sign in as admin user
7. Go to Urls/Catching URIs tab and create a rule `LauncherTemplate`, `/website/cms/urls`

### Expected result

The default behavior to be that a URI catched in LauncherTemplate is not additionaly catched in DefaultTemplate.

It can be achieved by adding a "Final" checkbox to the Urls/Catching URIs tab.

I think that if we add such checkbox then we can remove the "Default" checkbox from the Templates/Surfaces tab. It can be replaced by creating a catch-all rule in the Urls/Catching URIs tab, which will have an empty value in the URI input.

### Actual result

Right now this is the case that you get it wrapped first in LauncherTemplate, then in DefaultTemplate, because only a default template sets the value `IsFinal` to true.

### Screenshot

![2017-02-21 17_28_57-website running - microsoft visual studio](https://cloud.githubusercontent.com/assets/566463/23174059/797f9580-f85b-11e6-8c51-4d914c97b16d.png)

**Comment by un-tone** [comment]
Created PRs https://github.com/StarcounterPrefabs/Simplified/pull/45 and https://github.com/StarcounterPrefabs/Website/pull/43.
https://github.com/StarcounterPrefabs/Website/issues/44 must be fixed before resolving this.

**Comment by warpech** [comment]
I think that this can be closed before #44 is fixed. 

#44 blocks navigating from one surface to another, but that is another problem.

**Comment by un-tone** [comment]
Closing as done.
