### ISSUE TITLE
Website cannot change a Surface

### ISSUE THREAD

**Issue by un-tone** [StarcounterPrefabs/Website#44]
### Pre-requisites

1. Use `Simplified.Data.Model` assembly from the `feature/Add-IsFinal-property-WebUrl` branch of the `Simplified` repo

### Steps to reproduce

1. Start Website and WebsiteProvider (branch `feature/Add-IsFinal-property-CatchingURLs`)
2. Start SignIn branch `develop`
2. Call `http://localhost:8080/website/resetdata` to load default mappings
4. Go to `http://localhost:8080/signin/generateadminuser` to generate the admin user
5. Go to `http://localhost:8080/website/cms`
6. Sign in as admin user
7. Go to "Catching rules" tab and create rules:
    - `LauncherTemplate`, `/website/cms/catchingrules`
    - `LauncherTemplate`, `/website/cms/pinningrules`
8. Refresh the page
9. Go to `http://localhost:8080/website/cms/pinningrules`
10. Go to `http://localhost:8080/website/cms/blendingpoints`

### Expected result

The "Blending points" page is shown.

### Actual result

The URL in the browser is changed but still shown the "Pinning rules" page.

It seems like WebsiteProvider cannot change a Surface correctly.
For example, switching between "Catching rules" and "Pinning rules" pages works fine as same as switching between "Surfaces" and "Blending points". The issue appears when you are switching betwen pages with different Surfaces.

As I understand after investigating, the cause of such behaviour is incorrect work with Session in the `/WebsiteProvider/partial/layout` handler implemented in the WebsiteProvider.ContentHandlers class.

##### Involved apps' version

 - StarcounterPrefabs/Simplified@66f265e6619e071819cc096b34e259b4f5b38d5d
 - StarcounterPrefabs/Website@10808872dc94a8d1255b0fe2b3438d9bd8ca84d3
 - StarcounterPrefabs/SignIn@7b8e455c9a9805e587c01fb7ffc1dcc3f18740f2
 
### Screenshot
![image](https://cloud.githubusercontent.com/assets/1625378/23310468/b2c3fda8-fac3-11e6-9513-863353940ea7.png)

**Comment by un-tone** [comment]
@warpech could you please look at this?

**Comment by un-tone** [comment]
The issue is related to https://github.com/StarcounterPrefabs/Website/issues/41

**Comment by warpech** [comment]
Can you try investigating why this happens?

**Comment by un-tone** [comment]
Created PR https://github.com/StarcounterPrefabs/Website/pull/49

**Comment by un-tone** [comment]
Closing as done
